### PR TITLE
Add the ability to filter displayed dives

### PR DESCRIPTION
**Pull request by jamesnvc**

### CODE REVIEW

**Comment by jamesnvc** [comment]
Don't love the UI for this...but something to start the conversation.

**Comment by fysiskhund** [comment]
Cool! I also added a filter on my version in my repo.. but it's only filtering out between shallow and deep dives. Maybe we can combine everything, lol.

**Comment by jamesnvc** [comment]
Nice, I can add that in here too, that’s a good idea

**Comment by jamesnvc** [comment]
Okay! Added the ability to filter for depth as well, added a settings page to configure what is considered "deep" and "short"; also added the ability to set the display units & date format there.

**Pull request merged**
