### PR TITLE
Display average depth, max and minimum temperature in Export Dive

### PR DESCRIPTION
**Pull request by fysiskhund**
Also changed the title of the Export Dive Screen to Dive Summary Screen.

Slightly changed the querying mechanism so all the data could be gathered and assembled in the beginning.

Displaying this data as a summary is very useful for SSI App users. In the future I would like to add an SSI Dive QR code, if possible.

### CODE REVIEW

**Comment by fysiskhund** [comment]
Thank you very much for the base app, by the way. It is extremely useful :)

**Comment by djunkins** [comment]
> Also changed the title of the Export Dive Screen to Dive Summary Screen.
> 
> Slightly changed the querying mechanism so all the data could be gathered and assembled in the beginning.
> 
> Displaying this data as a summary is very useful for SSI App users. In the future I would like to add an SSI Dive QR code, if possible.

I'll take a look at this and, if everything looks good, merge the pull request. A cursory look at the the changes looks great -- I'm glad you were able to refactor the HealthKit query to grab both depth and temperature at the same time. I had added the temperature query after the fact and didn't think it through very well.

Please be patient -- I'm still a novice at Github workflows, so I may need a little time to figure the right process for testing and merging pull requests.

**Comment by fysiskhund** [comment]
Take your time :D 
Happy to contribute!

**Comment by djunkins** [comment]
Hey, I realized that I never got back to you about this pull request. I compiled it and was using it successfully, but it seems to add a pretty large delay displaying the list of dives once you start the app. I haven't merged the pull request in because of this, nor have I had much time to dig into where the delay is.

**Comment by fysiskhund** [comment]
Hey there! I believe the code does not "add" per se any delay, I believe the difference is that it makes you wait for all data to be populated before it becomes interactive, whereas your code adds the entries as it is reading them. I want to make it load only the key data (likely by maintaining it in a database instead of having to read and calculate all the things every time the app is opened), but I haven't gotten around to it.

Anyway it looks like James' might be the definitive version since it has way more features :P 
I haven't yet looked at it.

**Comment by djunkins** [comment]
I've moved forward with several of James' pull requests and I think this one could be refactored and resubmitted to work better with the current code base.

**Pull request closed without merging**
